name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  validate-terraform-syntax:
    name: Validate Terraform syntax (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Show Terraform version
        run: terraform -version
      - name: terraform-init
        run: terraform init -backend=false
      - name: terraform-validate
        run: terraform validate

  lint-terraform-syntax:
    name: Lint Terraform syntax (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Show Terraform version
        run: terraform -version
      - name: terraform-fmt
        run: terraform fmt -check -recursive

